name: StableDiffusion
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 18.1
  xcodeVersion: "16.2"

targets:
  StableDiffusion:
    type: application
    platform: iOS
    deploymentTarget: 
      iOS: 18.1
    sources:
      - path: StableDiffusion/Sources
        includes:
          - "**/*.swift"
      - path: StableDiffusion/Resources
        type: folder
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_NAME: StableDiffusion
        PRODUCT_BUNDLE_IDENTIFIER: com.example.stablediffusion
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "iPhone Developer"
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: Diffusion 203
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISceneConfigurations_UIWindowSceneSessionRoleApplication_UISceneDelegateClassName: StableDiffusion.SceneDelegate
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: armv7
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0.0
        INFOPLIST_KEY_CFBundleVersion: 1 